### ISSUE TITLE
capture bug when video publication is muted

### ISSUE THREAD

**Issue by alex-bluetrain** [livekit/livekit-recorder#22]
If you record in service mode a room using the templates (I tested with grid-dark) with only 1 participant, and that participant mutes the video publication but keeps the audio enabled, the resulting video capture will have problems at the portion where the video was muted, it will be skipped. It seems the framebuffer needs to be constantly updating to avoid that problem.

Just to confirm my theory, I modified the grid-dark template to have a spinner rolling all the time, and then the resulting video can playback correctly on the muted-video portion.

maybe related: There's a huge slowdown everytime the video is unmuted (even with the spinner fix) it starts dropping audio frames for a few seconds (WARNING - Can't record audio fast enough) right after unmuting the video publication. This happens at the start of the recording and every time I unmute the video. 

tested on livekit/livekit-recorder:v0.3.6

**Comment by frostbyte73** [comment]
I'll have to look into the first part, good call on the frame buffer.

The second part _should_ be fixed already in 0.3.7 - I wasn't able to reproduce it anymore after increasing queue sizes, but let me know if you still see it happening with v0.3.7

**Comment by alex-bluetrain** [comment]
thanks @frostbyte73 audio is working great on 0.3.7, it was the queue size 👍

**Comment by frostbyte73** [comment]
@alex-bluetrain video muting issues fixed in v0.3.13
