### ISSUE TITLE
Livekit Docker error and not recoding !

### ISSUE THREAD

**Issue by thusinh1969** [livekit/livekit-recorder#34]
We start a simple example and this is the error from docker log:

**+ rm -rf /var/run/pulse /var/lib/pulse /root/.config/pulse
+ pulseaudio -D --verbose --exit-idle-time=-1 --system --disallow-exit
W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
N: [pulseaudio] main.c: Running in system mode, forcibly disabling SHM mode.
I: [pulseaudio] main.c: Daemon startup successful.
+ pactl load-module module-null-sink sink_name=grab sink_properties=device.description=monitorOUT
10
+ pid=0
+ trap 'kill ${!}; term_handler' SIGTERM
+ pid=14
+ wait 14
+ XDG_RUNTIME_DIR=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.cache/xdgr
+ ./livekit-recorder
0:00:00.405171135   257 0x5591f5012930 ERROR            msdkcontext gstmsdkcontext.c:140:gst_msdk_context_use_vaapi: Couldn't find a drm device node to open

(gst-plugin-scanner:257): GStreamer-WARNING **: 12:09:00.203: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so': libva-wayland.so.2: cannot open shared object file: No such file or directory**

Nothing is being recorded as well although we join room and publish video using livekit-sdk-js.

Any hint ?

* Docker command:
docker run -d  --name dd5eb4d2-2a57-401b-890e-456704d787bd_00 \
  -e LIVEKIT_RECORDER_CONFIG="$(cat /home/nguyen/NhauOnline/api_livekit/recording/dd5eb4d2-2a57-401b-890e-456704d787bd/config.yaml)" \
  -e RECORDING_REQUEST="$(cat /home/nguyen/NhauOnline/api_livekit/recording/dd5eb4d2-2a57-401b-890e-456704d787bd/config.json)" \
  -v /home/nguyen/NhauOnline/api_livekit/recording/dd5eb4d2-2a57-401b-890e-456704d787bd:/out livekit/livekit-recorder -g "daemon off;"

* config.yaml
api_key: my_key
api_secret: my_secret
ws_url: ws://localhost:7880
log_level: info
redis:
    address: localhost:6379
    password: my_password
    db: 1
file_output:
    local: True

* config.json
{"template": {"layout": "speaker-dark", "room_name": "dd5eb4d2-2a57-401b-890e-456704d787bd"}, "filepath": "/out/dd5eb4d2-2a57-401b-890e-456704d787bd_00.mp4", "options": {"preset": "NONE", "width": 1920, "height": 1080, "depth": 24, "framerate": 30, "audio_bitrate": 128, "audio_frequency": 44100, "video_bitrate": 4500}}

Steve

**Comment by frostbyte73** [comment]
`(gst-plugin-scanner:257): GStreamer-WARNING : 12:09:00.203: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so': libva-wayland.so.2: cannot open shared object file: No such file or directory`
This error is unrelated/safe to ignore. How are you stopping the recording? If GStreamer doesn't get a chance to flush, the file will not work

**Comment by frostbyte73** [comment]
How are you stopping the recording? If GStreamer doesn't get a chance to flush, it won't complete the file and it won't be usable

**Comment by frostbyte73** [comment]
You cannot use a template to connect to `ws://localhost:7880` - your LiveKit server must be accessible over public internet. Updated README to reflect that.

**Comment by thusinh1969** [comment]
It works ! Thanks, BUT the mp4 can NOT be played with Windows Media Player, any reason why ?

Steve
