### ISSUE TITLE
Recorded video has codec format that is NOT recognized by Media Player and few others, except VLC

### ISSUE THREAD

**Issue by thusinh1969** [livekit/livekit-recorder#36]
![livekit](https://user-images.githubusercontent.com/35662216/145013184-ffbbf721-6d8f-4d88-8c67-9e7e4592e13c.png)

The above is what VLC codec information show the recorded video by LiveKit. While my setup was:
  "options" : {
      "preset": "FULL_HD_60",
      "width": 1920,
      "height": 1080,
      "depth": 24,
      "framerate": 60,
      "audio_bitrate": 128,
      "audio_frequency": 48000,
      "video_bitrate": 6000,
  }

Can you tell me what could have been wrong? I used https://example.livekit.io/ for testing. Video quality is bad (low fps only 16 ?!?!?), voice also not clear.

I intended to record VP8 (video) and OPUS (audio) later, any help is appreciated.

Thanks,
Steve

**Comment by frostbyte73** [comment]
Fixed in v0.3.12 - options to choose encoding profile, with `main` as default
