### ISSUE TITLE
Recorded file is empty - chrome_crashpad is executed

### ISSUE THREAD

**Issue by mheers** [livekit/livekit-recorder#41]
I needed to pass `--privileged` to circumvent the following error:
```
0:00:00.212961785   468 0x5565bfd7dcd0 ERROR            msdkcontext gstmsdkcontext.c:140:gst_msdk_context_use_vaapi: Couldn't find a drm device node to open
```

But then still the output `.mp4` is an empty file.

When I exec into the container I see that there are two `chrome_crashpad` process which probably indicate that something broke.

**Comment by frostbyte73** [comment]
vaapi errors are expected and can be ignored
https://github.com/livekit/livekit-recorder#im-seeing-gstreamer-errors-is-this-normal

**Comment by mheers** [comment]
I am fine with the error message, but the problem is that the recorded file is empty.

**Comment by frostbyte73** [comment]
@mheers it might be related to https://github.com/livekit/livekit-recorder/issues/22 (telltale sign of this is no errors logged, and a `Sending EOS to pipeline` message but no `EOS received` message. Are there any errors logged?

**Comment by mheers** [comment]
I'm testing to record a youtube video, like in the quick-start example.

The output is
```
docker run --rm --privileged --name quick-demo \ 
    -e LIVEKIT_RECORDER_CONFIG="$(cat config.yaml)" \
    -e RECORDING_REQUEST="$(cat request.json)" \
    -v /tmp/recordings:/out \
    livekit/livekit-recorder

+ rm -rf /var/run/pulse /var/lib/pulse /root/.config/pulse
+ pulseaudio -D --verbose --exit-idle-time=-1 --system --disallow-exit
W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
N: [pulseaudio] main.c: Running in system mode, forcibly disabling SHM mode.
I: [pulseaudio] main.c: Daemon startup successful.
+ pactl load-module module-null-sink sink_name=grab sink_properties=device.description=monitorOUT
10
+ pid=0
+ trap 'kill ${!}; term_handler' SIGTERM
+ pid=14
+ wait 14
+ XDG_RUNTIME_DIR=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.cache/xdgr
+ ./livekit-recorder
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0

(gst-plugin-scanner:284): GStreamer-WARNING **: 07:46:14.447: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so': libva-wayland.so.2: cannot open shared object file: No such file or directory
```

I'm running Ubuntu 20.04.3 LTS with 5.13.0-27-generic and docker 20.10.12

**Comment by hdmodha** [comment]
![Screenshot from 2022-02-08 16-53-53](https://user-images.githubusercontent.com/74590273/152978284-4e92d222-2ace-41b1-9caf-53f6480deee5.png)

I am getting the same error, have you solved it? 
1st one is " Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvaapi.so': libva-wayland.so.2: cannot open shared object file: No such file or directory " and
2nd is " msdkcontext gstmsdkcontext.c:140:gst_msdk_context_use_vaapi: Couldn't find a drm device node to open "

**Comment by frostbyte73** [comment]
@mheers @hdmodha try updating to v0.3.13, it includes a number of bug fixes

**Comment by mheers** [comment]
Awesome. It now works perfectly! Thank you very much!!
