### ISSUE TITLE
How to record a video stream specified in the room

### ISSUE THREAD

**Issue by lgcshy** [livekit/livekit-recorder#50]
Hello! I would like to ask if I want to record a video stream in the room (specify a Video Tarck ID), what should I do?
• Does this version support this feature? Or I need to create a new template. Thank you!

**Comment by iAmcR** [comment]
Hi. Any updates on this? In particular, I'd like to just record a (video and or audio only) stream in a particular room, without using templates. Can you point me as to how I could get this done, server-side?

**Comment by davidzhao** [comment]
almost there :) there'll be an announcement next week.

**Comment by michelandres** [comment]
Any update about this? thanks

**Comment by davidzhao** [comment]
@michelandres @iAmcR check out the Egress service, it supersedes recorder. The function you are looking for is TrackCompositeEgress or TrackEgress: https://docs.livekit.io/guides/egress/
