### ISSUE TITLE
not able to force recorded mp4 to custom framerate

### ISSUE THREAD

**Issue by tidoemanuele** [livekit/livekit-recorder#52]
Hi Guys,
I'm running the last version of livekit-server localy. 
With the android client sample-app everything works just fine for one or more participants. 
Now I need to record at the best quality a participant track. 
This is the running command I'm using:
  docker run --rm --network host --name local-demo     -e LIVEKIT_RECORDER_CONFIG="$(cat config.yaml)"     -e RECORDING_REQUEST="$(cat room.json)"     -v c:/temp/livekit/recordings:/out     livekit/livekit-recorder

The recording process works but the mp4 output has only ~9-10 fps
I need 30 ou 60 or get close to the best quality. How can I force it? I already tried several android devices, forcing FHD video preset on the android client and in the recording module I added this defaults values
defaults: 
  audio_bitrate: 128
  audio_frequency: 44100
  depth: 24
  framerate: 60
  height: 1080
  profile: main
  video_bitrate: 6000
  width: 1920

But it is still with low framerate. What I'm doing wrong?

**Comment by davidzhao** [comment]
@tidoemanuele that sounds really low.. does the resulting video appear choppy to you?

Which OS are you running this on? It's possible that Docker doesn't have access to sufficient CPUs on the machine.

**Comment by tidoemanuele** [comment]
The video appear with good quality to the participant device. I'm running the server and the livekit-recorder on Windows with Docker Desktop. 
Is it possible to force the livekit-recorder to record the video track with the highest quality?

**Comment by davidzhao** [comment]
How many CPUs are you allowing Docker Desktop to use? Compositing a room & encoding it is fairly resource intensive. If docker doesn't have sufficient resources, it'll degrade quality of recording.

**Comment by tidoemanuele** [comment]
I tried with (3 CPUs and 6GB RAM ) but it continues to store a mp4 with a very poor frame rate (5-10 fps)

**Comment by tidoemanuele** [comment]
I upgraded my server hardware and this issue disappeared. I'm able to record at 30fps without any issue
